#!/usr/bin/env bash
##
# Launches parsec in a container.

set -euo pipefail

xhost "local:root"

docker run -itd --rm --init \
  -u 0:0 \
  --env DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  --device /dev/dri \
  -v ~/.parsec:/root/.parsec \
  ghcr.io/jaredallard/docker-parsec:main app_daemon=1
